Use api-specification that supports multiple docs
digipost/signature-api-client-java pull request #174
Opened 2020-10-14 13:57 UTC by simenstoa

### 💰 Funksjonell beskrivelse av endringen

_På hvilken måte endrer applikasjonen opppførsel når denne koden merges inn? Tenk ingress!_

### 🏆 Interessante highlights

_Usikkerheter, avveininger og andre ting som kan være interessant å se på_

### 🤷‍♀️ Anbefalt fremgangsmåte

_Hvordan bør pull requesten angripes? Commit for commit? Hele smæla på en gang? Gjennomgang i fellesskap IRL?_

### 👀 Eksempler og screenshots

_Har du gjort en API-endring? Vis et request! Har du endret i GUI? Ta et screenshot!_

### ⚙️ Avhengigheter 

_Er koden avhengig av en endring i for eksempel frontend eller API-klienten? Sleng inn en link til relevante pull requests her_

2020-10-21 08:23 UTC, simenstoa commented on src/main/java/no/digipost/signature/client/core/SignatureJob.java
>      Document getDocument();
Default som kaller getDocuments(), og feiler om det er mer enn 1 dokument.

2020-10-21 08:25 UTC, simenstoa commented on src/main/java/no/digipost/signature/client/direct/DirectJob.java
>          return document;
Kan slettes pga default

2020-11-04 09:59 UTC, simenstoa commented on pom.xml
> +        <signature.api.version>multiple-documents-SNAPSHOT</signature.api.version>
Endre til releaset versjon når den kommer.

2021-06-09 14:29 UTC, sarawe approved these changes

2021-06-09 15:56 UTC, runeflobakk requested changes

2021-06-09 15:56 UTC, runeflobakk commented on pom.xml
> +
TODO: remove before merge/release.

2021-06-09 16:26 UTC, runeflobakk commented on pom.xml
> +        <signature.api.version>2.8-RC2</signature.api.version>
TODO: change to released version

2021-06-22 20:35 UTC, runeflobakk approved these changes

2021-06-22 20:35 UTC, merged